import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import { ThemeProvider } from '@/components/ui/ThemeProvider'
import Clientproviders from '@/components/Clientproviders'
import FirebaseAuthProvider from '@/components/FirebaseAuthProvider'
import SubscriptionProvider from '@/components/SubscriptionProvider'
import { Toaster } from '@/components/ui/toaster'
import NextTopLoader from 'nextjs-toploader';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Clientproviders>
    <html lang="en">
      <body className='flex flex-col min-h-screen'>
      <NextTopLoader 
      color="#dd225a"
  initialPosition={0.08}
  crawlSpeed={200}
  height={3}
  crawl={true}
  showSpinner={false}
  easing="ease"
  speed={200}
  shadow="0 0 10px #2299DD,0 0 5px #2299DD"
  template='<div class="bar" role="bar"><div class="peg"></div></div> 
  <div class="spinner" role="spinner"><div class="spinner-icon"></div></div>'
  zIndex={1600}
  showAtBottom={false}
      />
        <FirebaseAuthProvider>
          <SubscriptionProvider>
        <ThemeProvider 
        
        attribute='class'
        defaultTheme='system'
        enableSystem
        disableTransitionOnChange
        >

        <Header/>
        {children}
        <Toaster/>
        </ThemeProvider>
        </SubscriptionProvider>
        </FirebaseAuthProvider>
       </body>
    </html>
    </Clientproviders>
  )
}
